#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"


# Settings for bar apperence 
bar=( 
  height=35       
  blur_radius=30  
  position=top    
  sticky=off      
  padding_left=10 
  padding_right=10
  color=$BAR_COLOR
)

sketchybar --bar "${bar[@]}"

# Default settings 

default=(
  icon.font="SF Pro:Semibold:14.0"
  icon.color=$RED
  label.font="SF Pro:Semibold:13.0"
  label.color=$TEXT
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24 
  padding_left=5  
  padding_right=5  
  label.padding_left=3  
  label.padding_right=6
  icon.padding_left=6 
  icon.padding_right=3
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
# source $ITEM_DIR/spaces.sh
# source $ITEM_DIR/front_app.sh
source $ITEM_DIR/aerospace.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/brew.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

