general.import = [
    "~/.dotfiles/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[env]
TERM = "xterm-256color"

[window]

# decorations = "none"

padding.x = 10
padding.y = 10

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14
