#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true


[palette]
text = "#cad3f5"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
teal = "#8bd5ca"
maroon = "#ee99a0"
peach = "#f5a97f"


[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "os"
style = "plain"
foreground = "p:text"
background = "transparent"
template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} {{ .HostName }} ❯ "

[[blocks.segments]]
type = 'path'
style = "plain"
background = 'transparent'
foreground = 'p:red'
template = '{{ .Path }} ❯'

[blocks.segments.properties]
style = 'agnoster_short'
home_icon = " \ue617 "
folder_icon = " \ue5fe "
folder_separator_icon = " ❯ "

[[blocks.segments]]
type = "git"
style = "plain"
background = "transparent"
foreground = "p:peach"
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350> \uf046 {{ .Staging.String }}</>{{ end }} "
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:pink{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:maroon{{ end }}",
  "{{ if gt .Ahead 0 }}p:red{{ end }}",
  "{{ if gt .Behind 0 }}p:teal{{ end }}",
]

[blocks.segments.properties]
branch_icon = " \ue725 "
fetch_status = true
fetch_upstream_icon = true
source = "cli"

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}#8aadf4{{end}}",
  "{{if eq .Code 0}}#f5bde6{{end}}",
]
background = 'transparent'
template = '❯'

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}#8aadf4{{end}}",
  "{{if eq .Code 0}}#f5bde6{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'magenta'
background = 'transparent'
template = '❯❯ '
